//****************************************************************************
// Описание:
//   Фрейм для отображения миниатюр файлов хранящихся в ЛОЦМАН.
//   Фрейм прикрепляется к фрейму "Файлы" и показывает миниатюру выделенного
//   файла.
// Подключение:
//   1) С помощью конструктора компоновок создать компоновку вида:
//      Дерево->Файлы->PreviewFrame
//   2) В дереве выбрать документ, содержащий файлы
//   3) Во фрейме "Файлы" выбрать файл
//   Фрейм PreviewFrame отобразит миниатюру файла
//****************************************************************************
unit PreviewFrameWindowImpl;

{$WARN SYMBOL_PLATFORM OFF}

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  ActiveX, AxCtrls, PreviewFrame_TLB, StdVcl, Loodsman_tlb, StdCtrls, Variants, ExtCtrls, ShellObjHelper , jpeg, dxGDIPlusClasses,
  DataProvider_TLB;

type
  TPreviewFrameWindow = class(TActiveForm, IPreviewFrameWindow, IFrameInfo, ILoodsmanFrame )
    pnlPreview: TPanel;
    img1: TImage;
  {$REGION 'AutoGeneratedCode'}
  private
    { Private declarations }
    FEvents: IPreviewFrameWindowEvents;
    procedure ActivateEvent(Sender: TObject);
    procedure ClickEvent(Sender: TObject);
    procedure CreateEvent(Sender: TObject);
    procedure DblClickEvent(Sender: TObject);
    procedure DeactivateEvent(Sender: TObject);
    procedure DestroyEvent(Sender: TObject);
    procedure KeyPressEvent(Sender: TObject; var Key: Char);
    procedure MouseEnterEvent(Sender: TObject);
    procedure MouseLeaveEvent(Sender: TObject);
    procedure PaintEvent(Sender: TObject);
  protected
    { Protected declarations }
    procedure DefinePropertyPages(DefinePropertyPage: TDefinePropertyPage); override;
    procedure EventSinkChanged(const EventSink: IUnknown); override;
    function Get_Active: WordBool; safecall;
    function Get_AlignDisabled: WordBool; safecall;
    function Get_AlignWithMargins: WordBool; safecall;
    function Get_AutoScroll: WordBool; safecall;
    function Get_AutoSize: WordBool; safecall;
    function Get_AxBorderStyle: TxActiveFormBorderStyle; safecall;
    function Get_Caption: WideString; safecall;
    function Get_Color: OLE_COLOR; safecall;
    function Get_DockSite: WordBool; safecall;
    function Get_DoubleBuffered: WordBool; safecall;
    function Get_DropTarget: WordBool; safecall;
    function Get_Enabled: WordBool; safecall;
    function Get_ExplicitHeight: Integer; safecall;
    function Get_ExplicitLeft: Integer; safecall;
    function Get_ExplicitTop: Integer; safecall;
    function Get_ExplicitWidth: Integer; safecall;
    function Get_Font: IFontDisp; safecall;
    function Get_HelpFile: WideString; safecall;
    function Get_KeyPreview: WordBool; safecall;
    function Get_MouseInClient: WordBool; safecall;
    function Get_PixelsPerInch: Integer; safecall;
    function Get_PopupMode: TxPopupMode; safecall;
    function Get_PrintScale: TxPrintScale; safecall;
    function Get_Scaled: WordBool; safecall;
    function Get_ScreenSnap: WordBool; safecall;
    function Get_SnapBuffer: Integer; safecall;
    function Get_UseDockManager: WordBool; safecall;
    function Get_Visible: WordBool; safecall;
    function Get_VisibleDockClientCount: Integer; safecall;
    procedure _Set_Font(var Value: IFontDisp); safecall;
    procedure Set_AlignWithMargins(Value: WordBool); safecall;
    procedure Set_AutoScroll(Value: WordBool); safecall;
    procedure Set_AutoSize(Value: WordBool); safecall;
    procedure Set_AxBorderStyle(Value: TxActiveFormBorderStyle); safecall;
    procedure Set_Caption(const Value: WideString); safecall;
    procedure Set_Color(Value: OLE_COLOR); safecall;
    procedure Set_DockSite(Value: WordBool); safecall;
    procedure Set_DoubleBuffered(Value: WordBool); safecall;
    procedure Set_DropTarget(Value: WordBool); safecall;
    procedure Set_Enabled(Value: WordBool); safecall;
    procedure Set_Font(const Value: IFontDisp); safecall;
    procedure Set_HelpFile(const Value: WideString); safecall;
    procedure Set_KeyPreview(Value: WordBool); safecall;
    procedure Set_PixelsPerInch(Value: Integer); safecall;
    procedure Set_PopupMode(Value: TxPopupMode); safecall;
    procedure Set_PrintScale(Value: TxPrintScale); safecall;
    procedure Set_Scaled(Value: WordBool); safecall;
    procedure Set_ScreenSnap(Value: WordBool); safecall;
    procedure Set_SnapBuffer(Value: Integer); safecall;
    procedure Set_UseDockManager(Value: WordBool); safecall;
    procedure Set_Visible(Value: WordBool); safecall;
  public
    procedure Initialize; override;
    {$ENDREGION 'AutoGeneratedCode'}
  protected
  {IFrameInfo - Информация о фрейме}
    //Список кодов объектов, которые фрейм может принять
    function GetInTypes: WideString; safecall;

    //Код отдаваемых фреймом объектов
    function GetOutType: Integer; safecall;

    //Название фрейма (отображается в конструкторе компоновок)
    function GetFrameName: WideString; safecall;

    //Описание фрейма
    function GetFrameDescription: WideString; safecall;

    //Может ли фрейм быть корневым
    function IsRootFrame: WordBool; safecall;

  {ILoodsmanFrame - Жизненный цикл фрейма}
    //Создание фрейма
    procedure OnFrameCreate(const Context: IDBContext; const Container: IFrameContainer; const OwnerApplication: IDispatch); safecall;

    //Закрытие фрейма
    procedure OnFrameDestroy; safecall;

    //Получение фокуса
    procedure OnFrameActivate; safecall;

    //Потеря фокуса
    procedure OnFrameDeactivate; safecall;

    //Этот метод вызывается ЛОЦМАН Клиентом когда требуется обновить данные отображаемые фреймом
    procedure OnStartRefresh; safecall;

    //Очистка фрейма
    procedure OnFrameClear; safecall;

    //Метод зарезервирован, должен возвращать Null
    function OnCustomEvent(EventCode: Integer; EventData: OleVariant): OleVariant; safecall;

    //Загрузка параметров фрейма из компоновки
    procedure OnLoadOptions(const AFrameOptions: IOptions); safecall;

    //Сохранение параметров фрейма в компоновке
    procedure OnSaveOptions(const AFrameOptions: IOptions); safecall;


    {}
    //Показать миниатюру
    procedure ShowThumbnail(const FileName: String);
  public
    FContext: IDBContext;         //Интерфейс контекста MDI окна, в котором находится фрейм
    FContainer: IFrameContainer;  //Интерфейс контейнера содержащего фрейм.
    app: ILoodsmanApplication;    //Основной интерфейс ЛОЦМАН Клиента

  end;

implementation

uses ComObj, ComServ, PDMObjects_TLB;

{$R *.DFM}

{ TPreviewFrameWindow }

{$REGION 'AutoGeneratedCode'}

procedure TPreviewFrameWindow.DefinePropertyPages(DefinePropertyPage: TDefinePropertyPage);
begin
  { Define property pages here.  Property pages are defined by calling
    DefinePropertyPage with the class id of the page.  For example,
      DefinePropertyPage(Class_PreviewFrameWindowPage); }
end;

procedure TPreviewFrameWindow.EventSinkChanged(const EventSink: IUnknown);
begin
  FEvents := EventSink as IPreviewFrameWindowEvents;
  inherited EventSinkChanged(EventSink);
end;

procedure TPreviewFrameWindow.Initialize;
begin
  inherited Initialize;
  OnActivate := ActivateEvent;
  OnClick := ClickEvent;
  OnCreate := CreateEvent;
  OnDblClick := DblClickEvent;
  OnDeactivate := DeactivateEvent;
  OnDestroy := DestroyEvent;
  OnKeyPress := KeyPressEvent;
  OnMouseEnter := MouseEnterEvent;
  OnMouseLeave := MouseLeaveEvent;
  OnPaint := PaintEvent;
end;

function TPreviewFrameWindow.Get_Active: WordBool;
begin
  Result := Active;
end;

function TPreviewFrameWindow.Get_AlignDisabled: WordBool;
begin
  Result := AlignDisabled;
end;

function TPreviewFrameWindow.Get_AlignWithMargins: WordBool;
begin
  Result := AlignWithMargins;
end;

function TPreviewFrameWindow.Get_AutoScroll: WordBool;
begin
  Result := AutoScroll;
end;

function TPreviewFrameWindow.Get_AutoSize: WordBool;
begin
  Result := AutoSize;
end;

function TPreviewFrameWindow.Get_AxBorderStyle: TxActiveFormBorderStyle;
begin
  Result := Ord(AxBorderStyle);
end;

function TPreviewFrameWindow.Get_Caption: WideString;
begin
  Result := WideString(Caption);
end;

function TPreviewFrameWindow.Get_Color: OLE_COLOR;
begin
  Result := OLE_COLOR(Color);
end;

function TPreviewFrameWindow.Get_DockSite: WordBool;
begin
  Result := DockSite;
end;

function TPreviewFrameWindow.Get_DoubleBuffered: WordBool;
begin
  Result := DoubleBuffered;
end;

function TPreviewFrameWindow.Get_DropTarget: WordBool;
begin
  Result := DropTarget;
end;

function TPreviewFrameWindow.Get_Enabled: WordBool;
begin
  Result := Enabled;
end;

function TPreviewFrameWindow.Get_ExplicitHeight: Integer;
begin
  Result := ExplicitHeight;
end;

function TPreviewFrameWindow.Get_ExplicitLeft: Integer;
begin
  Result := ExplicitLeft;
end;

function TPreviewFrameWindow.Get_ExplicitTop: Integer;
begin
  Result := ExplicitTop;
end;

function TPreviewFrameWindow.Get_ExplicitWidth: Integer;
begin
  Result := ExplicitWidth;
end;

function TPreviewFrameWindow.Get_Font: IFontDisp;
begin
  GetOleFont(Font, Result);
end;

function TPreviewFrameWindow.Get_HelpFile: WideString;
begin
  Result := WideString(HelpFile);
end;

function TPreviewFrameWindow.Get_KeyPreview: WordBool;
begin
  Result := KeyPreview;
end;

function TPreviewFrameWindow.Get_MouseInClient: WordBool;
begin
  Result := MouseInClient;
end;

function TPreviewFrameWindow.Get_PixelsPerInch: Integer;
begin
  Result := PixelsPerInch;
end;

function TPreviewFrameWindow.Get_PopupMode: TxPopupMode;
begin
  Result := Ord(PopupMode);
end;

function TPreviewFrameWindow.Get_PrintScale: TxPrintScale;
begin
  Result := Ord(PrintScale);
end;

function TPreviewFrameWindow.Get_Scaled: WordBool;
begin
  Result := Scaled;
end;

function TPreviewFrameWindow.Get_ScreenSnap: WordBool;
begin
  Result := ScreenSnap;
end;

function TPreviewFrameWindow.Get_SnapBuffer: Integer;
begin
  Result := SnapBuffer;
end;

function TPreviewFrameWindow.Get_UseDockManager: WordBool;
begin
  Result := UseDockManager;
end;

function TPreviewFrameWindow.Get_Visible: WordBool;
begin
  Result := Visible;
end;

function TPreviewFrameWindow.Get_VisibleDockClientCount: Integer;
begin
  Result := VisibleDockClientCount;
end;

procedure TPreviewFrameWindow._Set_Font(var Value: IFontDisp);
begin
  SetOleFont(Font, Value);
end;

procedure TPreviewFrameWindow.ActivateEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnActivate;
end;

procedure TPreviewFrameWindow.ClickEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnClick;
end;

procedure TPreviewFrameWindow.CreateEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnCreate;
end;

procedure TPreviewFrameWindow.DblClickEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnDblClick;
end;

procedure TPreviewFrameWindow.DeactivateEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnDeactivate;
end;

procedure TPreviewFrameWindow.DestroyEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnDestroy;
end;

procedure TPreviewFrameWindow.KeyPressEvent(Sender: TObject; var Key: Char);
var
  TempKey: Smallint;
begin
  TempKey := Smallint(Key);
  if FEvents <> nil then FEvents.OnKeyPress(TempKey);
  Key := Char(TempKey);
end;

procedure TPreviewFrameWindow.MouseEnterEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnMouseEnter;
end;

procedure TPreviewFrameWindow.MouseLeaveEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnMouseLeave;
end;

procedure TPreviewFrameWindow.PaintEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnPaint;
end;

procedure TPreviewFrameWindow.Set_AlignWithMargins(Value: WordBool);
begin
  AlignWithMargins := Value;
end;

procedure TPreviewFrameWindow.Set_AutoScroll(Value: WordBool);
begin
  AutoScroll := Value;
end;

procedure TPreviewFrameWindow.Set_AutoSize(Value: WordBool);
begin
  AutoSize := Value;
end;

procedure TPreviewFrameWindow.Set_AxBorderStyle(Value: TxActiveFormBorderStyle);
begin
  AxBorderStyle := TActiveFormBorderStyle(Value);
end;

procedure TPreviewFrameWindow.Set_Caption(const Value: WideString);
begin
  Caption := TCaption(Value);
end;

procedure TPreviewFrameWindow.Set_Color(Value: OLE_COLOR);
begin
  Color := TColor(Value);
end;

procedure TPreviewFrameWindow.Set_DockSite(Value: WordBool);
begin
  DockSite := Value;
end;

procedure TPreviewFrameWindow.Set_DoubleBuffered(Value: WordBool);
begin
  DoubleBuffered := Value;
end;

procedure TPreviewFrameWindow.Set_DropTarget(Value: WordBool);
begin
  DropTarget := Value;
end;

procedure TPreviewFrameWindow.Set_Enabled(Value: WordBool);
begin
  Enabled := Value;
end;

procedure TPreviewFrameWindow.Set_Font(const Value: IFontDisp);
begin
  SetOleFont(Font, Value);
end;

procedure TPreviewFrameWindow.Set_HelpFile(const Value: WideString);
begin
  HelpFile := string(Value);
end;

procedure TPreviewFrameWindow.Set_KeyPreview(Value: WordBool);
begin
  KeyPreview := Value;
end;

procedure TPreviewFrameWindow.Set_PixelsPerInch(Value: Integer);
begin
  PixelsPerInch := Value;
end;

procedure TPreviewFrameWindow.Set_PopupMode(Value: TxPopupMode);
begin
  PopupMode := TPopupMode(Value);
end;

procedure TPreviewFrameWindow.Set_PrintScale(Value: TxPrintScale);
begin
  PrintScale := TPrintScale(Value);
end;

procedure TPreviewFrameWindow.Set_Scaled(Value: WordBool);
begin
  Scaled := Value;
end;

procedure TPreviewFrameWindow.Set_ScreenSnap(Value: WordBool);
begin
  ScreenSnap := Value;
end;

procedure TPreviewFrameWindow.Set_SnapBuffer(Value: Integer);
begin
  SnapBuffer := Value;
end;

procedure TPreviewFrameWindow.Set_UseDockManager(Value: WordBool);
begin
  UseDockManager := Value;
end;

procedure TPreviewFrameWindow.Set_Visible(Value: WordBool);
begin
  Visible := Value;
end;
{$ENDREGION 'AutoGeneratedCode'}

{IFrameInfo}

function TPreviewFrameWindow.GetInTypes: WideString; safecall;
begin
  Result := IntToStr(C_FILE);  // дочерний для фреймов, которые содержат файлы
end;

function TPreviewFrameWindow.GetOutType: Integer; safecall;
begin
  Result := -1;    // не может быть родительским
end;

function TPreviewFrameWindow.GetFrameName: WideString; safecall;
begin
  Result := 'PreviewFrame'; //Имя фрейма отображаемое в конструкторе компоновок
end;

function TPreviewFrameWindow.GetFrameDescription: WideString; safecall;
begin
  Result := 'PreviewFrame Description';
end;

function TPreviewFrameWindow.IsRootFrame: WordBool; safecall;
begin
  Result := False;       // не может быть корневым
end;

  {ILoodsmanFrame}

procedure TPreviewFrameWindow.OnFrameCreate(const Context: IDBContext; const Container: IFrameContainer; const OwnerApplication: IDispatch); safecall;
begin
  //Запомним параметры окружения
  FContext:= Context;
  FContainer:=Container;
  app:= OwnerApplication as ILoodsmanApplication;
end;

procedure TPreviewFrameWindow.OnFrameDestroy; safecall;
begin
  FContext:= nil;
  FContainer:= nil;
  app:= nil;
end;

procedure TPreviewFrameWindow.OnFrameActivate; safecall;
begin
end;

procedure TPreviewFrameWindow.OnFrameDeactivate; safecall;
begin
end;

//Один из самых важных методов жизненного цикла фрейма. ЛОЦМАН Клиент
//вызывает его, когда необходимо обновить иформацию отображаемую фреймом.
//Это происходит при загрузке фрейма, при смене выделенного в родительском
//фрейме объекта (в данном случае во фрейме "Файлы), при нажатии
//кнопки "Обновить" и т.д.
procedure TPreviewFrameWindow.OnStartRefresh; safecall;
var ParentFrameContainer : IFrameContainer;
    ParentFrameContainerContent : IContent;
    pdmdata : IPDMData;
    PDMFile : iPDMFile;
    stFilename : string;
begin
  img1.Picture.Bitmap := nil;
  ParentFrameContainer := Self.FContainer.ParentFrame; //Получаем родительский фрейм
  if ParentFrameContainer<>nil then
  begin
    ParentFrameContainerContent := ParentFrameContainer.Content;  //Содержимое родительского фрейма
    if ParentFrameContainerContent.SelectedCount > 0 then
    begin
      //Проверим действительно ли выделенный объект файл
      if idispatch(ParentFrameContainerContent.SelectedByIndex(0)).QueryInterface(IID_IPDMFile, PDMFile)= s_ok  then
      begin
        try
           //Для демонстрации вызова методов сервера приложений выгрузим файл так
           stFilename := (FContext.Connection as ISimpleAPI2).RunMethod('ExtractFile', VarArrayOf(['','','', PDMFile.Document.ID, PDMFile.Name, PDMFile.LocalName, 1]));
           //stFileName := PDMFile.Load; 
           ShowThumbnail(stFilename); //Рисуем миниатюру
        except
        end;
      end;
    end;
  end;
end;

procedure TPreviewFrameWindow.OnFrameClear; safecall;
begin
end;
function  TPreviewFrameWindow.OnCustomEvent(EventCode: Integer; EventData: OleVariant): OleVariant; safecall;
begin
end;
procedure TPreviewFrameWindow.OnLoadOptions(const AFrameOptions: IOptions); safecall;
begin
end;
procedure TPreviewFrameWindow.OnSaveOptions(const AFrameOptions: IOptions); safecall;
begin
end;



procedure TPreviewFrameWindow.ShowThumbnail(const FileName: String);
var XtractImage: IExtractImage;
    Bmp: TBitmap;
    Icon: TIcon;
    ColorDepth: Integer;
    Flags: DWORD;
    RT: IRunnableTask;
    jpgImg: TJPEGImage;
    res : Integer;
const
  dwLocationFlags = IEIFLAG_ASPECT or IEIFLAG_OFFLINE or IEIFLAG_SCREEN
                 or IEIFLAG_QUALITY or IEIFLAG_ORIGSIZE;
begin
  res := -1;
  if not FileExists(FileName) then
    Exit;  // выход с ошибкой
  ColorDepth := 32;
  Flags := dwLocationFlags;
  Bmp := nil;
  Icon := nil;
  try
    try
      if GetExtractImageItfPtr(FileName, XTractImage) and ExtractImageGetFileThumbnail(XtractImage, 256, 256, ColorDepth, Flags, RT, Bmp) then
        res := 0
      else
      if GetFileLargeIcon(FileName, Icon) and (Icon <> nil) and (bmp <> nil) then
        begin
          bmp.Height := Icon.Height;
          bmp.Width := Icon.Width;
          bmp.Canvas.Draw(0, 0, icon);
          res := 0;

        end;

      if Assigned(bmp) then
        img1.Picture.Bitmap := Bmp;

    except
      res := -1;
    end;
  finally
    if Assigned(Icon) then
      Icon.Free;
    if Assigned(Bmp) then
      Bmp.Free;
  end;
end;




initialization
  TActiveFormFactory.Create(
    ComServer,
    TActiveFormControl,
    TPreviewFrameWindow,
    Class_PreviewFrameWindow,
    1,
    '',
    OLEMISC_SIMPLEFRAME or OLEMISC_ACTSLIKELABEL,
    tmApartment);
end.
