unit SuprStatWindowImpl;

{$WARN SYMBOL_PLATFORM OFF}

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  ActiveX, AxCtrls, PreviewFrame_TLB, loodsman_tlb, TeEngine, Series, ExtCtrls, TeeProcs, Chart, StdVcl, supr_tlb , DateUtils;

type
  TSuprStatWindow = class(TActiveForm, ISuprStatWindow, IFrameInfo, ILoodsmanFrame )
    scrlbx1: TScrollBox;
    chtStatePie: TChart;
    pieStarSeries1: TPieSeries;
    chtPieWorkers: TChart;
    PieWorkersSeries1: TPieSeries;
    chtErrors: TChart;
    PieErrorsSeries1: TPieSeries;

  {$REGION 'AutoGeneratedCode'}
  private
    { Private declarations }
    FEvents: ISuprStatWindowEvents;
    procedure ActivateEvent(Sender: TObject);
    procedure ClickEvent(Sender: TObject);
    procedure CreateEvent(Sender: TObject);
    procedure DblClickEvent(Sender: TObject);
    procedure DeactivateEvent(Sender: TObject);
    procedure DestroyEvent(Sender: TObject);
    procedure KeyPressEvent(Sender: TObject; var Key: Char);
    procedure MouseEnterEvent(Sender: TObject);
    procedure MouseLeaveEvent(Sender: TObject);
    procedure PaintEvent(Sender: TObject);
  protected
    { Protected declarations }
    procedure DefinePropertyPages(DefinePropertyPage: TDefinePropertyPage); override;
    procedure EventSinkChanged(const EventSink: IUnknown); override;
    function Get_Active: WordBool; safecall;
    function Get_AlignDisabled: WordBool; safecall;
    function Get_AlignWithMargins: WordBool; safecall;
    function Get_AutoScroll: WordBool; safecall;
    function Get_AutoSize: WordBool; safecall;
    function Get_AxBorderStyle: TxActiveFormBorderStyle; safecall;
    function Get_Caption: WideString; safecall;
    function Get_Color: OLE_COLOR; safecall;
    function Get_DockSite: WordBool; safecall;
    function Get_DoubleBuffered: WordBool; safecall;
    function Get_DropTarget: WordBool; safecall;
    function Get_Enabled: WordBool; safecall;
    function Get_ExplicitHeight: Integer; safecall;
    function Get_ExplicitLeft: Integer; safecall;
    function Get_ExplicitTop: Integer; safecall;
    function Get_ExplicitWidth: Integer; safecall;
    function Get_Font: IFontDisp; safecall;
    function Get_HelpFile: WideString; safecall;
    function Get_KeyPreview: WordBool; safecall;
    function Get_MouseInClient: WordBool; safecall;
    function Get_PixelsPerInch: Integer; safecall;
    function Get_PopupMode: TxPopupMode; safecall;
    function Get_PrintScale: TxPrintScale; safecall;
    function Get_Scaled: WordBool; safecall;
    function Get_ScreenSnap: WordBool; safecall;
    function Get_SnapBuffer: Integer; safecall;
    function Get_UseDockManager: WordBool; safecall;
    function Get_Visible: WordBool; safecall;
    function Get_VisibleDockClientCount: Integer; safecall;
    procedure _Set_Font(var Value: IFontDisp); safecall;


    procedure Set_AlignWithMargins(Value: WordBool); safecall;
    procedure Set_AutoScroll(Value: WordBool); safecall;
    procedure Set_AutoSize(Value: WordBool); safecall;
    procedure Set_AxBorderStyle(Value: TxActiveFormBorderStyle); safecall;
    procedure Set_Caption(const Value: WideString); safecall;
    procedure Set_Color(Value: OLE_COLOR); safecall;
    procedure Set_DockSite(Value: WordBool); safecall;
    procedure Set_DoubleBuffered(Value: WordBool); safecall;
    procedure Set_DropTarget(Value: WordBool); safecall;
    procedure Set_Enabled(Value: WordBool); safecall;
    procedure Set_Font(const Value: IFontDisp); safecall;
    procedure Set_HelpFile(const Value: WideString); safecall;
    procedure Set_KeyPreview(Value: WordBool); safecall;
    procedure Set_PixelsPerInch(Value: Integer); safecall;
    procedure Set_PopupMode(Value: TxPopupMode); safecall;
    procedure Set_PrintScale(Value: TxPrintScale); safecall;
    procedure Set_Scaled(Value: WordBool); safecall;
    procedure Set_ScreenSnap(Value: WordBool); safecall;
    procedure Set_SnapBuffer(Value: Integer); safecall;
    procedure Set_UseDockManager(Value: WordBool); safecall;
    procedure Set_Visible(Value: WordBool); safecall;
  public
    procedure Initialize; override;
  {$ENDREGION 'AutoGeneratedCode'}

  protected
    function GetFrameDescription: WideString; safecall;
    function GetFrameName: WideString; safecall;
    function GetInTypes: WideString; safecall;
    function GetOutType: Integer; safecall;
    function IsRootFrame: WordBool; safecall;

    procedure OnFrameActivate; safecall;
    procedure OnFrameClear; safecall;
    procedure OnFrameCreate(const Context: IDBContext; const Container: IFrameContainer; const OwnerApplication: IDispatch); safecall;
    procedure OnFrameDeactivate; safecall;
    procedure OnFrameDestroy; safecall;
    procedure OnLoadOptions(const AFrameOptions: IOptions); safecall;
    procedure OnSaveOptions(const AFrameOptions: IOptions); safecall;
    procedure OnStartRefresh; safecall;
    function OnCustomEvent(EventCode: Integer; EventData: OleVariant): OleVariant; safecall;
  public
    FContext: IDBContext;
    FContainer: IFrameContainer;
    app: iloodsmanapplication;
  end;

implementation

uses ComObj, ComServ, PDMObjects_TLB;

{$R *.DFM}

const
    // цвета состояний

  tckGray = $99959A; // tsNew      msNew
  tckBlue = $FF9B00; // tsIssued
  tckgreen = $0DB530; // tsPerformed
  tckDarkPink = $9933CC; // tsPaused
  tckOrange = $008EFF; // tsCompleted   msPassed
  tckDarkRed = $000099; // tsArchive
  tckBrown = $006699; // tsCancelled
  tckRED = $0000FF; //



  statesnames : array[tsNew..tsChecking] of  string = (
  'Новые',
  'Выданы',
  'Выполняются',
  'Приостановлены',
  'Завершены',
  'В архиве',
  'Отменены',
  'Запланированы',
  'Достигнуты',
  'На проверке'
  );




  statecolors  : array[tsNew..tsChecking] of  Tcolor = (
  tckGray,
  tckBlue     ,
  tckgreen    ,
  tckDarkPink ,
  tckOrange   ,
  tckDarkRed  ,
  tckBrown    ,
  tckGray     ,
  tckOrange   ,
  tckRED



  );



{ TSuprStatWindow }

{$REGION 'AutoGeneratedCode'}
procedure TSuprStatWindow.DefinePropertyPages(DefinePropertyPage: TDefinePropertyPage);
begin
  { Define property pages here.  Property pages are defined by calling
    DefinePropertyPage with the class id of the page.  For example,
      DefinePropertyPage(Class_SuprStatWindowPage); }
end;

procedure TSuprStatWindow.EventSinkChanged(const EventSink: IUnknown);
begin
  FEvents := EventSink as ISuprStatWindowEvents;
  inherited EventSinkChanged(EventSink);
end;

procedure TSuprStatWindow.Initialize;
begin
  inherited Initialize;
  OnActivate := ActivateEvent;
  OnClick := ClickEvent;
  OnCreate := CreateEvent;
  OnDblClick := DblClickEvent;
  OnDeactivate := DeactivateEvent;
  OnDestroy := DestroyEvent;
  OnKeyPress := KeyPressEvent;
  OnMouseEnter := MouseEnterEvent;
  OnMouseLeave := MouseLeaveEvent;
  OnPaint := PaintEvent;
end;

function TSuprStatWindow.Get_Active: WordBool;
begin
  Result := Active;
end;

function TSuprStatWindow.Get_AlignDisabled: WordBool;
begin
  Result := AlignDisabled;
end;

function TSuprStatWindow.Get_AlignWithMargins: WordBool;
begin
  Result := AlignWithMargins;
end;

function TSuprStatWindow.Get_AutoScroll: WordBool;
begin
  Result := AutoScroll;
end;

function TSuprStatWindow.Get_AutoSize: WordBool;
begin
  Result := AutoSize;
end;

function TSuprStatWindow.Get_AxBorderStyle: TxActiveFormBorderStyle;
begin
  Result := Ord(AxBorderStyle);
end;

function TSuprStatWindow.Get_Caption: WideString;
begin
  Result := WideString(Caption);
end;

function TSuprStatWindow.Get_Color: OLE_COLOR;
begin
  Result := OLE_COLOR(Color);
end;

function TSuprStatWindow.Get_DockSite: WordBool;
begin
  Result := DockSite;
end;

function TSuprStatWindow.Get_DoubleBuffered: WordBool;
begin
  Result := DoubleBuffered;
end;

function TSuprStatWindow.Get_DropTarget: WordBool;
begin
  Result := DropTarget;
end;

function TSuprStatWindow.Get_Enabled: WordBool;
begin
  Result := Enabled;
end;

function TSuprStatWindow.Get_ExplicitHeight: Integer;
begin
  Result := ExplicitHeight;
end;

function TSuprStatWindow.Get_ExplicitLeft: Integer;
begin
  Result := ExplicitLeft;
end;

function TSuprStatWindow.Get_ExplicitTop: Integer;
begin
  Result := ExplicitTop;
end;

function TSuprStatWindow.Get_ExplicitWidth: Integer;
begin
  Result := ExplicitWidth;
end;

function TSuprStatWindow.Get_Font: IFontDisp;
begin
  GetOleFont(Font, Result);
end;

function TSuprStatWindow.Get_HelpFile: WideString;
begin
  Result := WideString(HelpFile);
end;

function TSuprStatWindow.Get_KeyPreview: WordBool;
begin
  Result := KeyPreview;
end;

function TSuprStatWindow.Get_MouseInClient: WordBool;
begin
  Result := MouseInClient;
end;

function TSuprStatWindow.Get_PixelsPerInch: Integer;
begin
  Result := PixelsPerInch;
end;

function TSuprStatWindow.Get_PopupMode: TxPopupMode;
begin
  Result := Ord(PopupMode);
end;

function TSuprStatWindow.Get_PrintScale: TxPrintScale;
begin
  Result := Ord(PrintScale);
end;

function TSuprStatWindow.Get_Scaled: WordBool;
begin
  Result := Scaled;
end;

function TSuprStatWindow.Get_ScreenSnap: WordBool;
begin
  Result := ScreenSnap;
end;

function TSuprStatWindow.Get_SnapBuffer: Integer;
begin
  Result := SnapBuffer;
end;

function TSuprStatWindow.Get_UseDockManager: WordBool;
begin
  Result := UseDockManager;
end;

function TSuprStatWindow.Get_Visible: WordBool;
begin
  Result := Visible;
end;

function TSuprStatWindow.Get_VisibleDockClientCount: Integer;
begin
  Result := VisibleDockClientCount;
end;

procedure TSuprStatWindow._Set_Font(var Value: IFontDisp);
begin
  SetOleFont(Font, Value);
end;

procedure TSuprStatWindow.ActivateEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnActivate;
end;

procedure TSuprStatWindow.ClickEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnClick;
end;

procedure TSuprStatWindow.CreateEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnCreate;
end;

procedure TSuprStatWindow.DblClickEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnDblClick;
end;

procedure TSuprStatWindow.DeactivateEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnDeactivate;
end;

procedure TSuprStatWindow.DestroyEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnDestroy;
end;

procedure TSuprStatWindow.KeyPressEvent(Sender: TObject; var Key: Char);
var
  TempKey: Smallint;
begin
  TempKey := Smallint(Key);
  if FEvents <> nil then FEvents.OnKeyPress(TempKey);
  Key := Char(TempKey);
end;

procedure TSuprStatWindow.MouseEnterEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnMouseEnter;
end;

procedure TSuprStatWindow.MouseLeaveEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnMouseLeave;
end;

procedure TSuprStatWindow.PaintEvent(Sender: TObject);
begin
  if FEvents <> nil then FEvents.OnPaint;
end;

procedure TSuprStatWindow.Set_AlignWithMargins(Value: WordBool);
begin
  AlignWithMargins := Value;
end;

procedure TSuprStatWindow.Set_AutoScroll(Value: WordBool);
begin
  AutoScroll := Value;
end;

procedure TSuprStatWindow.Set_AutoSize(Value: WordBool);
begin
  AutoSize := Value;
end;

procedure TSuprStatWindow.Set_AxBorderStyle(Value: TxActiveFormBorderStyle);
begin
  AxBorderStyle := TActiveFormBorderStyle(Value);
end;

procedure TSuprStatWindow.Set_Caption(const Value: WideString);
begin
  Caption := TCaption(Value);
end;

procedure TSuprStatWindow.Set_Color(Value: OLE_COLOR);
begin
  Color := TColor(Value);
end;

procedure TSuprStatWindow.Set_DockSite(Value: WordBool);
begin
  DockSite := Value;
end;

procedure TSuprStatWindow.Set_DoubleBuffered(Value: WordBool);
begin
  DoubleBuffered := Value;
end;

procedure TSuprStatWindow.Set_DropTarget(Value: WordBool);
begin
  DropTarget := Value;
end;

procedure TSuprStatWindow.Set_Enabled(Value: WordBool);
begin
  Enabled := Value;
end;

procedure TSuprStatWindow.Set_Font(const Value: IFontDisp);
begin
  SetOleFont(Font, Value);
end;

procedure TSuprStatWindow.Set_HelpFile(const Value: WideString);
begin
  HelpFile := string(Value);
end;

procedure TSuprStatWindow.Set_KeyPreview(Value: WordBool);
begin
  KeyPreview := Value;
end;

procedure TSuprStatWindow.Set_PixelsPerInch(Value: Integer);
begin
  PixelsPerInch := Value;
end;

procedure TSuprStatWindow.Set_PopupMode(Value: TxPopupMode);
begin
  PopupMode := TPopupMode(Value);
end;

procedure TSuprStatWindow.Set_PrintScale(Value: TxPrintScale);
begin
  PrintScale := TPrintScale(Value);
end;

procedure TSuprStatWindow.Set_Scaled(Value: WordBool);
begin
  Scaled := Value;
end;

procedure TSuprStatWindow.Set_ScreenSnap(Value: WordBool);
begin
  ScreenSnap := Value;
end;

procedure TSuprStatWindow.Set_SnapBuffer(Value: Integer);
begin
  SnapBuffer := Value;
end;

procedure TSuprStatWindow.Set_UseDockManager(Value: WordBool);
begin
  UseDockManager := Value;
end;

procedure TSuprStatWindow.Set_Visible(Value: WordBool);
begin
  Visible := Value;
end;
{$ENDREGION 'AutoGeneratedCode'}

function TSuprStatWindow.GetFrameDescription: WideString;
begin
  Result := 'SuprStat Description';
end;

function TSuprStatWindow.GetFrameName: WideString;
begin
  Result := 'SuprStat';
end;

function TSuprStatWindow.GetInTypes: WideString;
begin
  Result := IntToStr(C_TASK);
end;

function TSuprStatWindow.GetOutType: Integer;
begin
  Result := -1;
end;

function TSuprStatWindow.IsRootFrame: WordBool;
begin
  Result := False;
end;

function TSuprStatWindow.OnCustomEvent(EventCode: Integer; EventData: OleVariant): OleVariant;
begin
end;

procedure TSuprStatWindow.OnFrameActivate;
begin
end;

procedure TSuprStatWindow.OnFrameClear;
begin
end;

procedure TSuprStatWindow.OnFrameCreate(const Context: IDBContext; const Container: IFrameContainer; const OwnerApplication: IDispatch);
begin
   FContext := Context;
   FContainer:= Container;
   app:=  OwnerApplication as iloodsmanapplication;
end;

procedure TSuprStatWindow.OnFrameDeactivate;
begin
end;

procedure TSuprStatWindow.OnFrameDestroy;
begin
   FContext := nil;
   FContainer:= nil;
   app:=  nil;
end;

procedure TSuprStatWindow.OnLoadOptions(const AFrameOptions: IOptions);
begin
end;

procedure TSuprStatWindow.OnSaveOptions(const AFrameOptions: IOptions);
begin
end;

procedure TSuprStatWindow.OnStartRefresh;
type
   stateData = record
     TotalCount : integer;
     TotalplanDuration : double;
   end;


var parentt, t : Itask;
    tt : ITasks;
    i : Integer;
    statesdata : array[tsNew..tsChecking] of  stateData;
    Workers : TStringList;
    wname : string;
    windex : Integer;

    countCancelled,
    countNormal,
    countNotFinished,
    countNotStarted,
    countNotSent : Integer;

    (*

  tsNew = $00000000;
  tsIssued = $00000001;
  tsPerformed = $00000002;
  tsPaused = $00000003;
  tsCompleted = $00000004;
  tsArchive = $00000005;
  tsCancelled = $00000006;
  tsScheduled = $00000007;
  tsReached = $00000008;
  tsChecking = $00000009;            *)



  function getworkerDisplayName(w :IUser): string;
  begin
     Result := w.FullName ;
     if Result = '' then Result := w.Name;
  end;

begin



     Workers :=TStringList.Create;
     try




         for I := Low(statesdata) to High(statesdata) do
            begin
              statesdata[i].TotalCount :=0;
              statesdata[i].TotalplanDuration :=0;
            end;



         parentt := idispatch(FContainer.ParentFrame.Content.Selected) as ITask;
         tt := parentt.ExpandedSubtasks;
         for I := 0 to tt.Count - 1 do
           begin
             t := tt.Items[i];



             if ( t.Summary=0 ) and (t.IsMilestone=false) then
                begin
                   // задаяи по состояниям
                   inc(statesdata[t.State].TotalCount );
                   statesdata[t.State].TotalplanDuration := statesdata[t.State].TotalplanDuration + t.PlanDuration;
                   // по ошибкам
                   case t.State of
                        // невыданные
                        tsNew             :
                          if t.PlanDateStart < now then
                            inc(countNotSent)
                          else
                            inc(countNormal) ;
                        // непринятые
                        tsIssued          :
                          if t.PlanDateStart < now then
                            inc(countNotStarted)
                          else
                            inc(countNormal) ;

                        // не завершены
                        tsPerformed  ,
                        tsPaused     ,
                        tsChecking        :
                          if t.PlanDateFinish < now then
                            inc(countNotFinished)
                          else
                            inc(countNormal) ;
                        // заверешены вовремя?
                        tsArchive,
                        tsCompleted       :
                          if  startoftheday(t.PlanDateFinish) < startoftheday(t.DateFinish) then
                            inc(countNotFinished)
                          else
                            inc(countNormal) ;
                        tsCancelled       : inc(countCancelled)
                        ;
                   end;



                   // по исполнителям
                   wname := getworkerDisplayName(t.Worker);
                   windex := Workers.IndexOf(wname);
                   if windex= -1 then
                     begin
                        windex := Workers.Add(wname);
                        Workers.Objects[windex] := Pointer(0);
                     end;
                    Workers.Objects[windex] := Pointer( integer(Workers.Objects[windex]) +   Round(t.PlanDuration));



                end;
           end;

        //------------
        pieStarSeries1.Clear;

         for I := Low(statesdata) to High(statesdata) do
             if statesdata[i].TotalCount <> 0 then
                  pieStarSeries1.AddPie(statesdata[i].TotalCount, statesnames[i], statecolors[i]);


        //------
        PieWorkersSeries1.Clear;
        for I := 0 to Workers.Count - 1 do
              PieWorkersSeries1.Add(integer(Workers.Objects[i]),Workers[i] );

        //------
        PieErrorsSeries1.Clear;
        if countNormal>0 then PieErrorsSeries1.AddPie(countNormal, 'По плану', clGreen);
        if countCancelled>0 then    PieErrorsSeries1.AddPie(countCancelled, 'Отменены', statecolors[tsCancelled] );
        if countNotFinished>0 then PieErrorsSeries1.AddPie(countNotFinished, 'Просрочены', clRed);
        if countNotStarted>0 then PieErrorsSeries1.AddPie(countNotStarted, 'Не начаты', statecolors[tsIssued]);
        if countNotSent>0 then PieErrorsSeries1.AddPie(countNotSent, 'Не выданы', statecolors[tsnew]);





     finally
       FreeAndNil(Workers);

     end;

end;

initialization
  TActiveFormFactory.Create(
    ComServer,
    TActiveFormControl,
    TSuprStatWindow,
    Class_SuprStatWindow,
    2,
    '',
    OLEMISC_SIMPLEFRAME or OLEMISC_ACTSLIKELABEL,
    tmApartment);
end.
